# Generated by Django 4.0 on 2022-01-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('api_base_url', models.CharField(default=None, max_length=250)),
                ('api_service_name', models.CharField(default=None, max_length=50)),
                ('default_company', models.TextField(default=None, max_length=30)),
                ('tenant_id', models.TextField(default=None, max_length=30, null=True)),
                ('api_username', models.CharField(default=None, max_length=50)),
                ('api_pass', models.CharField(default=None, max_length=50)),
                ('keepass_uuid', models.TextField()),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
