# Generated by Django 4.0 on 2021-12-14 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApiResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('api_url', models.URLField()),
                ('api_username', models.CharField(max_length=50)),
                ('api_pass', models.CharField(max_length=50)),
                ('keepass_uuid', models.TextField()),
                ('description', models.CharField(max_length=300)),
                ('log_date', models.DateTimeField(verbose_name='date logged')),
            ],
        ),
    ]
