# Generated by Django 4.0 on 2021-12-27 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresource',
            name='description',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
