# Generated by Django 4.0 on 2022-01-13 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('camtapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiresource',
            name='tenant_id',
            field=models.TextField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
